name: deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile
      - run: git config --global user.email "$(git log -n 1 --pretty=format:%ae)"
      - run: git config --global user.name "$(git log -n 1 --pretty=format:%an)"
      - run: yarn deploy
